Update mainwindow.py
if self.recent is None (at the first start), MNELAB otherwise crashes with this error message:

Traceback (most recent call last):
[...]
  File "/opt/Software4EEG/MNE/lib/python3.12/site-packages/mnelab/mainwindow.py", line 78, in __init__
    self.recent = [recent for recent in self.recent if recent is not None]
[...]
TypeError: 'NoneType' object is not iterable